### ISSUE TITLE
MP4 filename error. Unicode/Ascii encoding related [Linux]

### ISSUE THREAD

**Issue by noobcoder2196** [kallqvist/skillshare-downloader#2]
Hey man, sorry for bugging you again :P 
So I shifted to a linux environment because the program is optimized for it, I guess. 
(It kept throwing errors on windows that I didn't have the energy to work on.)
Everything was working absolutely fine but this one time around when I was downloading a course this happened:

![skillshare-dl-bug3](https://user-images.githubusercontent.com/33173680/33048502-0ca7cfb0-ce7d-11e7-9d30-09999807fba0.png)

I did a quick search and found it has something to do with using the str() function on line 58 in downloader.py. Is a quick fix possible by using an alternative function? If you need an account cookie to test the code, you can use mine :)

Cheers mate :+1:

**Comment by kallqvist** [comment]
no worries :)
I changed these lines:
https://github.com/kallqvist/skillshare-downloader/commit/ca35a5e1033b869cf833439734266f7436b1eb33

It's a quick-n-dirty fix and I haven't tested this code but I think it should do the job.
The problem is "fancy tilted quotes" like these:
http://www.fileformat.info/info/unicode/char/2018/index.htm
http://www.fileformat.info/info/unicode/char/2019/index.htm

I'm having them replaced and then using encode/replace to make anything else not supported by ascii into ?'s.

Let me know if there was any typos in this commit or if it didn't do the job!
