### ISSUE TITLE
Exception: Failed to read video ID from data

### ISSUE THREAD

**Issue by icxruus** [kallqvist/skillshare-downloader#36]
After downloading a course, this error keeps appearing when I try to download another one
I checked that the cookie was ok and it is (it's the same I used with the other course)

**Comment by rockethubble** [comment]
Hi it only downloads the 1st video of the Course then this is the error.

    raise Exception('Failed to read video ID from data')
Exception: Failed to read video ID from data

**Comment by icxruus** [comment]
> Hi it only downloads the 1st video of the Course then this is the error.
> 
> ```
> raise Exception('Failed to read video ID from data')
> ```
> 
> Exception: Failed to read video ID from data

yeah, that's just what happens to me

**Comment by kallqvist** [comment]
Hmm... It does sound like an issue with the cookie or skillshare account. This is exactly what usually happens when either the cookie have expired or when the skillshare account no longer have access to skillshare premium videos on the account.
First video is usually free and available to everyone so it will download fine.
I have merged pull-request #37 since this was opened and from discussions it seems to have been working for a bunch of people that have experienced similar issues so will close this issue for now
